### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by xeeek** [kratos1812/csgo-antirush#2]
For some reason it doesn't work. I figured out the config, it was not created by itself, I had to do it manually. But nothing kills when entering the zone.
"Zones"
{
	"0"
	{
		"name"		"antirush_tr_test"
		"cordinate_a"		"-1539.934937 623.031250 -179.635132"
		"cordinate_b"		"-14.031250 715.910828 67.176895"
		"vis"		"1"
		"team"		"2"
	}
	"1"
	{
		"name"		"antirush_ct_test"
		"cordinate_a"		"-4.031250 1264.490112 -179.413559"
		"cordinate_b"		"-1529.969116 1177.456055 67.480453"
		"vis"		"1"
		"team"		"3"
	}
}
"sm_csgo_antirush_remove_time": "15999"

**Comment by kratos1812** [comment]
What is the name of the config file?

**Comment by xeeek** [comment]
$2000$_pro.zones.txt
When adding new zones, they are added to the file, everything is fine. But it does not repel or kill when entering them.

**Comment by kratos1812** [comment]
Are there any error logs?

**Comment by xeeek** [comment]
The error logs are clean.

**Comment by kratos1812** [comment]
Is that a workshop map btw?

**Comment by xeeek** [comment]
Yes, the workshop map.
Let it be up to the config - dev_zones/workshop/1849271236/$2000$_pro.zones.txt

**Comment by kratos1812** [comment]
Understood. Does this only happens with sm_csgo_antirush_punishment = 1?

**Comment by xeeek** [comment]
I've already tried everything. And 0 put, and 1. Does not kill and does not overlap.

**Comment by kratos1812** [comment]
Hmm strange, on my server everything works fine. On official maps with the provided configs.

Make sure the plugins are loaded.

sm plugins load csgo_antirush 
sm plugins load devzones

**Comment by xeeek** [comment]
![изображение](https://user-images.githubusercontent.com/52924403/121747573-ab635700-cb18-11eb-9b71-431df22c197a.png)

**Comment by kratos1812** [comment]
Yes but try to also reload them. I don't really know what is happenind and I might just add a debug convar for this.

**Comment by xeeek** [comment]
Let's try it.

sm_csgo_antirush_enable "1"
sm_csgo_antirush_punishment "1"
sm_csgo_antirush_remove_on_plant "0"
sm_csgo_antirush_remove_time "15999"
sm_csgo_antirush_rush_last_man "2"

**Comment by xeeek** [comment]
Also in the description there is an error sm_zone, not sm_zones
![изображение](https://user-images.githubusercontent.com/52924403/121905623-6834fe00-cd3b-11eb-8c05-0710ddacd8f1.png)
Also in the description there is an error sm_zone, not sm_zones
And some of the quars have already been cut out.

**Comment by xeeek** [comment]
The problem is solved. But a new one has appeared. In some cases, the zone just skips.
As an idea, you can add a point to kill a player if he is in the zone.

**Comment by xeeek** [comment]
The problem was, by the way, that the plugin had to be recompiled. As I understand it, the old version was compiled.

**Comment by kratos1812** [comment]
so i need to update the .smx file in the rep, thanks for your contribution

and sorry, I completely forgot about this
